export const LOGIN_FACEBOOK_REQUEST = "AUTH.LOGIN_FACEBOOK_REQUEST";
export const LOGIN_FACEBOOK_SUCCESS = "AUTH.LOGIN_FACEBOOK_SUCCESS";
export const LOGIN_FACEBOOK_FAILURE = "AUTH.LOGIN_FACEBOOK_FAILURE";
